In [1]:
import pandas as pd
df_visits = pd.read_csv('visits_1k.csv')
df_regs = pd.read_csv('regs_1k.csv')
print(f"Загружено визитов: {len(df_visits)}")
print(f"Загружено регистраций: {len(df_regs)}")

Загружено визитов: 1000
Загружено регистраций: 1000

In [2]:
print("Статистика для визитов:")
display(df_visits.describe(include='all'))

print("\nСтатистика для регистраций:")
display(df_regs.describe(include='all'))

Статистика для визитов:

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01T08:01:45
freq,4,954,71,2

Статистика для регистраций:

,date,user_id,email,platform,registration_type
count,1000,1.000000e+03,1000,1000,1000
unique,1000,NaN,997,3,4
top,2023-03-05T11:17:41,NaN,kimberly90@example.com,android,email
freq,1,NaN,2,517,446
mean,NaN,4.488623e+06,NaN,NaN,NaN
std,NaN,2.620568e+06,NaN,NaN,NaN
min,NaN,2.236800e+04,NaN,NaN,NaN
25%,NaN,2.235489e+06,NaN,NaN,NaN
50%,NaN,4.473044e+06,NaN,NaN,NaN
75%,NaN,6.779707e+06,NaN,NaN,NaN
max,NaN,8.881772e+06,NaN,NaN,NaN

In [11]:
import requests
import pandas as pd

url_visits = " https://data-charts-api.hexlet.app/visits?begin=2023-03-01&end=2023-09-01"
url_regs = "https://data-charts-api.hexlet.app/registrations?begin=2023-03-01&end=2023-09-01"

response_visits = requests.get(url_visits)
response_regs = requests.get(url_regs)

data_visits = response_visits.json()
data_regs = response_regs.json()

df_api_visits = pd.DataFrame(data_visits)
df_api_regs = pd.DataFrame(data_regs)

print(f"Из API успешно загружено визитов: {len(df_api_visits)}")
print(f"Из API успешно загружено регистраций: {len(df_api_regs)}")

Из API успешно загружено визитов: 263459
Из API успешно загружено регистраций: 21836